apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: felidae-nodejs 
  janus-idp.io/tekton: felidae-nodejs
  backstage.io/kubernetes-id: felidae-nodejs
  backstage.io/kubernetes-namespace: rhtap-test-organization-jk 
  app.kubernetes.io/part-of: felidae-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  